### ISSUE TITLE
No module named 'modal'

### ISSUE THREAD

**Issue by noname-oni** [semicognitive/sveltekit-modal#1]
## Environment
I'm using VScode on Windows.

## Error
Running `npm run dev` I'm getting an error:
```
from modal import Image, Secret, Mount, SharedVolume, Proxy
ModuleNotFoundError: No module named 'modal'
```

Seems it's an error with my Python environment. Looks weird to me that in the traceback it runs from `python3.8`:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/mnt/{PROJECT_PATH}/node_modules/sveltekit-modal/esm/src/vite/sveltekit_modal/__init__.py", line 1, in <module>
    from .config import Config  # For export
  File "/mnt/{PROJECT_PATH}/node_modules/sveltekit-modal/esm/src/vite/sveltekit_modal/config.py", line 3, in <module>
    from modal import Image, Secret, Mount, SharedVolume, Proxy
ModuleNotFoundError: No module named 'modal'
 ```
 
 But I have only installed `python3.11`. Any ideas on how I can fix this?

**Comment by ConProgramming** [comment]
Hey! Did you follow the instructions from [modal.com](https://modal.com) to set up an account? Make sure you have their library installed.
`pip install modal-client`

**Comment by noname-oni** [comment]
@ConProgramming yeah, the module was installed successfully. I even added a new token.

**Comment by ConProgramming** [comment]
> @ConProgramming yeah, the module was installed successfully. I even added a new token.

Hmm, try `pip3 install modal-client`? Could be that pip and pip3 differ on your system?

**Comment by noname-oni** [comment]
@ConProgramming doesn't help. Nevermind, python in VScode is hell

**Comment by ConProgramming** [comment]
> @ConProgramming doesn't help. Nevermind, python in VScode is hell 

Windows is rough too 🙏

**Comment by mraghuram** [comment]
@cogscides  Make sure you execute the code within the Py environment that you have installed the modal. I got the same issues, instead of install modal globally I created a conda environment installed and then ran npm run dev in that environment. 

@ConProgramming - I am getting a new error 'ImportError: cannot import name '_show_stub_ref_failure_help' from 'modal.cli.app'. Can you throw some light on this?

**Comment by auser** [comment]
@mraghuram I'm also hitting that error 

`ImportError: cannot import name '_show_stub_ref_failure_help' from 'modal.cli.app'`

Any idea why that's happening? Looking through `modal.cli.app` it doesn't look like there's a property `_show_stub_ref_failure_help` Versioning?

**Comment by auser** [comment]
This is on start-up.

It errors out when trying to actually call out... that fails when call generate with "can't create modal"

**Comment by auser** [comment]
@mraghuram or @ConProgramming did you get this figured out yet?

**Comment by ConProgramming** [comment]
> @mraghuram or @ConProgramming did you get this figured out yet?
> 
> 

It's possible it's the location where you have `modal` installed. We call `python3` directly, but I'm happy to accept a PR for adding a config option for the python cli location.

**Comment by auser** [comment]
@ConProgramming I mean't the error: `ImportError: cannot import name '_show_stub_ref_failure_help' from 'modal.cli.app'`

**Comment by auser** [comment]
@ConProgramming It's not actually an issue with finding `modal`, the imports don't exist in my package and not in the package on github...

When you run `python` in your terminal (REPL), can you actually import `_show_stub_ref_failure_help`?

Here's what my repl shows for `modal.cli` and below for `modal.cli.app`:

![python repl](https://user-images.githubusercontent.com/529/226716516-7b189a4e-2470-42c1-8980-7ee96607756b.png)

![modal.cli.app](https://user-images.githubusercontent.com/529/226716847-41424c6e-4bc7-4e2b-9158-95e9aba129f6.png)

**Comment by ConProgramming** [comment]
> @ConProgramming It's not actually an issue with finding `modal`, the imports don't exist in my package and not in the package on github...
> 
> When you run `python` in your terminal (REPL), can you actually import `_show_stub_ref_failure_help`?
> 
> Here's what my repl shows for `modal.cli` and below for `modal.cli.app`:
> 
> ![python repl](https://user-images.githubusercontent.com/529/226716516-7b189a4e-2470-42c1-8980-7ee96607756b.png)
> 
> ![modal.cli.app](https://user-images.githubusercontent.com/529/226716847-41424c6e-4bc7-4e2b-9158-95e9aba129f6.png)

What's the full stack trace? Not sure where `_show_stub_ref_failure_help` is being imported

**Comment by auser** [comment]
@ConProgramming it's in the src: `src/vite/sveltekit_modal/src/serve.py`

**Comment by ConProgramming** [comment]
> @ConProgramming it's in the src: `src/vite/sveltekit_modal/src/serve.py`

Ah yes
Weird it didn't show up in GitHub search

Modal might've changed their internals, you can try rolling back your modal cli version to when this was published (~ a month ago). I'll look to see what the NoSuchStub error message should be now.

**Comment by auser** [comment]
@ConProgramming It works with `0.45.1100`

**Comment by ConProgramming** [comment]
> @ConProgramming It works with `0.45.1100`

Awesome, thank you!

**Comment by ConProgramming** [comment]
Closing this, as it seems to be just python environment errors
