### ISSUE TITLE
Deprecated stuff disables deployment

### ISSUE THREAD

**Issue by rpruizc** [semicognitive/sveltekit-modal#6]
Hello team,
 I cannot deploy anything when using the sveltekit library as I get the following error:
 ```
 DeprecationError: Deprecated on 2023-04-18: `stub.asgi_app` is deprecated and no longer supported. Use `modal.asgi_app` instead
``` 
 The config file is the suggested one on this example:
 ```
 import modal

config = {
    'name': 'metriq-dashboard',
    'log': False,
    'stub_asgi': {
        'image': modal.Image.debian_slim().pip_install("python-multipart", "gpt-index", "langchain", "openai", "pylibmagic", "pypdf"),
        'secret': modal.Secret.from_name("my-openai-secret")
    }
}
``` 
 Is there anything I can do on my config file to avoid calling stub. and instead call modal. ?

Thanks in advance!

**Comment by ConProgramming** [comment]
Hey! As Modal keeps changing the internals of their library, as of right now you have to use an older version of `modal-client`, as I describe at https://github.com/semicognitive/sveltekit-modal/issues/4#issuecomment-1557696687.

I'm planning to update the code here to match the latest `modal-client` soon.
